name: Deployment workflow with 1 job
on: push
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Install all the dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Build the code
        run: npm run build
      - name: Deploy
        run: echo "Yehuu, we did it"