name: Deployment
on: push
jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run link
        run: npm run lint

