name: Deployment
on: push
jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  test:
    needs: lint
    runs-on: windows-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
  deploy:
    needs: [lint, test]
    runs-on: windows-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Install all the dependencies
        run: npm ci
      - name: Build the code
        run: npm run build
      - name: Deploy
        run: echo "Yehuu, we did it"



