name: Risen Issues
on: issues
jobs:
  info:
    runs-on: windows-latest
    steps:
      - name: Output information
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"